stages:
  - Unit_Tests
  - Code_Analysis
  - Dependency_Scan
  - Build
  - Update_Manifest
  # - Deploy
  # - Dynamic_Scan

variables:
  IMAGE_NAME: $DOCKER_USERNAME/netflix-clone
  IMAGE_TAG: $CI_PIPELINE_IID
  STAGING_URL: "http://13.60.217.236:3000"

# -------------------------
# UNIT TESTS
# -------------------------
Unit_Tests:
  stage: Unit_Tests
  image: node:18-alpine
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week

# -------------------------
# SONARQUBE ANALYSIS
# -------------------------
sonarqube_check:
  stage: Code_Analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - >
      sonar-scanner
      -Dsonar.projectKey=Ashen-Maneth_Netflix-project
      -Dsonar.organization=ashen-maneth
      -Dsonar.sources=.
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.token=$SONAR_TOKEN
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
# -------------------------
# DEPENDENCY SCAN
# -------------------------
owasp_dependency_scan:
  stage: Dependency_Scan
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh
      --project "Netflix-Clone" 
      --scan . 
      --format "HTML" 
      --out . 
      --disableNodeAudit
      --disableYarnAudit  
      --nvdApiKey $NVD_API_KEY
  artifacts:
    paths:
      - dependency-check-report.html
    expire_in: 1 week
  allow_failure: true

# -------------------------
# BUILD -> SCAN -> PUSH
# -------------------------
build_scan_push_image:
  stage: Build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # 1. Log into Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # 2. Install Trivy into this temporary Docker container
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    # Step 1: Build the image
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    
    # Step 2: Scan the image BEFORE pushing
    # (--exit-code 1 means if it finds High/Critical bugs, it stops and FAILS the pipeline right here)
    - trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_NAME:latest
    
    # Step 3: If the scan above passes safely, push to Docker Hub!
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest



    # -------------------------
# AUTO-UPDATE GITOPS REPO
# -------------------------
update_gitops_repo:
  stage: Update_Manifest
  image: alpine/git
  script:
    - sed -i "s/tag: .*/tag: $CI_PIPELINE_IID/g" netflix-chart/values.yaml
    - git config user.email "gitlab-bot@example.com"
    - git config user.name "GitLab CI Bot"
    - git add netflix-chart/values.yaml
    - git commit -m "Auto-update image tag to $CI_PIPELINE_IID [skip ci]"
    - git remote set-url origin https://oauth2:$GITLAB_TOKEN@gitlab.com/Ashen-Maneth/Netflix-project.git
    - git push origin main






















    

# # -------------------------
# # DEPLOY TO EC2
# # -------------------------
# deploy_to_k8s:
#   stage: Deploy
#   image: 
#     name: bitnami/kubectl:latest
#     entrypoint: [""] 
#   script:
#     - export KUBECONFIG=$KUBE_CONFIG_FILE 
#     - kubectl set image deployment/netflix-clone-deployment netflix-container=$IMAGE_NAME:latest 

# # -------------------------
# # DYNAMIC SECURITY SCAN
# # -------------------------
# owasp_zap_scan:
#   stage: Dynamic_Scan
#   image:
#     name: zaproxy/zap-stable
#     entrypoint: [""]
#   script:
#     - mkdir -p /zap/wrk
#     - zap-baseline.py -t $STAGING_URL -r zap-report.html || true
#     - cp /zap/wrk/zap-report.html ./zap-report.html
#   artifacts:
#     paths:
#       - zap-report.html
#     expire_in: 1 week
#   allow_failure: true